user.topic: user_topic
server:
  port: 8081
spring:
  kafka:
    consumer:
      group-id: user-group
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      bootstrap-servers: localhost:9092

  data:
    mongodb:
#      Uncomment this line if you want to use mongo in docker
#      uri: mongodb://localhost:27017/kafka-sample
      uri: mongodb+srv://mongodb:Ikdk1chGxkFEHvoa@cluster0.e10w7.gcp.mongodb.net/kafka-sample?retryWrites=true&w=majority