spring:
  kafka:
    producer:
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 1
      compression-type: gzip
    bootstrap-servers: localhost:9092